name: release

on:
  release:
    type: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run:
          sudo apt update && sudo apt install -y debhelper

      - name: Set env
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: build package
        run: |
          make package
          gh release upload ${TAG} $(echo ../* | tr ' ' '\n' | grep -v '^../yproxy$' | tr '\n' ' ')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}